'use client';

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Provider } from 'react-redux';

import { ToastContainer } from 'react-toastify';
import { store } from '@/redux/store';
import { ReactQueryProvider } from './providers/ReactQueryProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Provider store={store}>
            <Navbar />
            {children}
            <ToastContainer />
            <Footer />
          </Provider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
